import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { approveContracts } from "../src/approval.js";
import { createEvidenceBundle, createExecutionContext, createTaskPackage, stableHash, type RouteBindingInput, type TaskPackageInput } from "../src/contracts.js";
import { PRICING_CATALOG_HASH, PRICING_CATALOG_VERSION } from "../src/cost.js";
import { buildRouteBinding, createProjectPolicy, createUserPolicy, resolveEffectivePolicy } from "../src/policy.js";
import { assertPilotRunRecord, createPilotPairReport, createPilotRunRecordFromEvidence, persistPilotRunRecord, readPilotRunRecord, type PilotRunDerivationInput } from "../src/pilot-report.js";
import type { AttemptRecord, EvidenceBundle, ProviderTransportRound } from "../src/types.js";

const CONTENT = "a".repeat(64); const COMMIT = "1".repeat(40); const SNAPSHOT = "2".repeat(64); const FIXTURE = "3".repeat(64); const CREATED = "2026-08-24T08:00:00.000Z";
const budget = { max_attempts: 3, max_provider_requests: 6, max_input_tokens: 4_000, max_output_tokens: 1_000, max_tool_calls: 2, max_request_wall_time_ms: 30_000, max_wall_time_ms: 300_000, max_estimated_cost_usd: 0.25, billing_mode: "prepaid" as const };

function taskInput(): TaskPackageInput { return { version: 1, task_id: "pilot-task", goal: "Update a synthetic parser fixture.", background_summary: "Synthetic public fixture.", acceptance_criteria: ["Visible and hidden checks pass"], non_goals: ["No network"], forbidden_actions: ["No real provider"], read_scope: ["src/a.ts"], write_scope: ["src/a.ts"], relevant_interfaces: ["parse"], context_manifest: [{ path: "src/a.ts", kind: "file", selector: null, content_hash: CONTENT, source: "synthetic_fixture", byte_length: 1, summary: "Synthetic fixture." }], validation_requirements: ["visible", "hidden"], stop_conditions: ["Scope change"], data_classification: "public", egress_policy: { mode: "allow", providers: ["deepseek"], paths: ["src/a.ts"], content_hashes: [CONTENT], authorization_id: "synthetic-approval", authorized_by: "user", authorized_at: CREATED, expires_at: null }, request_budget: budget, created_at: CREATED }; }
function routeInput(): Omit<RouteBindingInput, "pricing_catalog_version" | "pricing_catalog_hash"> { return { version: 1, provider_id: "deepseek", adapter_id: "deepseek-direct", model_id: "deepseek-v4-flash", endpoint_origin: "https://api.deepseek.com", endpoint_path: "/chat/completions", wire_protocol: "chat_completions", auth_alias: "synthetic-alias", reasoning_mode: "disabled", reasoning_effort: "none", request_budget: budget, read_scope: ["src/a.ts"], write_scope: ["src/a.ts"], network_scope: ["https://api.deepseek.com"], environment_scope: [], command_scope: [] }; }

function fixture(options: { arm?: "gpt_only" | "hybrid"; hiddenFailed?: boolean; duplicate?: boolean; noTelemetry?: boolean } = {}): PilotRunDerivationInput {
  const task = createTaskPackage(taskInput());
  const user = createUserPolicy({ version: 1, policy_id: "pilot-user", egress_policy: task.egress_policy, read_scope: ["src/a.ts"], write_scope: ["src/a.ts"], budget_ceiling: budget });
  const project = createProjectPolicy({ version: 1, policy_id: "pilot-project", egress_policy: { mode: "allow", providers: ["deepseek"], paths: ["src/a.ts"], content_hashes: [CONTENT] }, read_scope: ["src/a.ts"], write_scope: ["src/a.ts"], budget_ceiling: budget });
  const policy = resolveEffectivePolicy(user, project); const route = buildRouteBinding(routeInput(), task, policy, new Date(CREATED));
  const execution = createExecutionContext({ version: 1, run_id: options.arm === "gpt_only" ? "gpt-run" : "hybrid-run", task_id: task.task_id, base_commit: COMMIT, main_workspace_snapshot: SNAPSHOT, main_workspace_dirty_evidence: [], worktree_id: "pilot-worktree", worktree_base: COMMIT, policy_hash: policy.policy_hash, task_package_hash: task.task_package_hash, route_binding_hash: route.route_binding_hash, created_at: CREATED });
  const approval = approveContracts({ taskPackage: task, routeBinding: route, executionContext: execution, effectivePolicy: policy }, { approvalId: "pilot-approval", approvedAt: new Date(CREATED) });
  const count = options.duplicate ? 2 : 1; const noTelemetry = options.noTelemetry ?? false;
  const rounds: ProviderTransportRound[] = noTelemetry ? [] : Array.from({ length: count }, (_, sequence) => ({ round_id: `round-${sequence}`, sequence, stage: "EXECUTE", request_id: `request-${sequence}`, started_at: CREATED, completed_at: "2026-08-24T08:00:00.010Z", wall_clock_time_ms: 10, response_model: route.model_id, response_origin: route.endpoint_origin, response_path: route.endpoint_path, http_status: 200, outcome: "SUCCEEDED", failure_class: null, usage: { input_tokens: 1, output_tokens: 1, reasoning_tokens: 0, cached_input_tokens: 0, cache_write_tokens: 0, cache_hit_tokens: 0, cache_miss_tokens: 1 }, cache_status: "miss", provider_reported_cost_usd: null, estimated_list_cost_usd: 0.00000176, pricing_catalog_version: PRICING_CATALOG_VERSION, pricing_catalog_hash: PRICING_CATALOG_HASH, pricing_time_band: "peak" }));
  const attempts: AttemptRecord[] = Array.from({ length: count }, (_, index) => ({ version: 1, attempt_id: `attempt-${index}`, run_id: execution.run_id, stage: "EXECUTE", round: index, request_fingerprint: stableHash({ same: true }), status: noTelemetry ? "PREPARED" : "SUCCEEDED", prepared_at: CREATED, send_started_at: noTelemetry ? null : CREATED, completed_at: noTelemetry ? null : "2026-08-24T08:00:00.010Z", failure_class: "none", provider_request_id: noTelemetry ? null : `request-${index}`, response_model: noTelemetry ? null : route.model_id, response_origin: noTelemetry ? null : route.endpoint_origin, usage: noTelemetry ? null : rounds[index]!.usage, transport_rounds: noTelemetry ? [] : [rounds[index]!], provider_reported_cost_usd: null, estimated_list_cost_usd: noTelemetry ? null : 0.00000176, redacted_error: null }));
  const qualityPolicyBody = { version: 1 as const, policy_id: "pilot-quality", command_ids: ["unit_tests", "project_acceptance"] as const, command_registry_hash: stableHash(["synthetic-visible", "synthetic-hidden"]), max_diff_bytes: 1024, max_file_bytes: 1024, max_output_bytes: 1024, max_wall_time_ms: 300_000 }; const qualityPolicy = { ...qualityPolicyBody, command_ids: [...qualityPolicyBody.command_ids], policy_hash: stableHash(qualityPolicyBody) };
  const gates = ["base_identity", "preapply_scope", "changed_files_scope", "forbidden_paths", "secret_scan", "diff_sanity", "format_check", "lint", "typecheck", "unit_tests", "build", "project_acceptance", "final_freeze", "evidence_artifact", "gate_budget"].map(gate_id => ({ gate_id, outcome: (gate_id === "unit_tests" ? "passed" : gate_id === "project_acceptance" ? options.hiddenFailed ? "failed" : "passed" : ["format_check", "lint", "typecheck", "build"].includes(gate_id) ? "not_applicable" : "passed") as "passed" | "failed" | "not_applicable", evidence_hash: stableHash({ gate_id }), summary: "synthetic" }));
  const boundaryHash = "b".repeat(64);
  const request = { run_id: execution.run_id, task_id: task.task_id, base_commit: COMMIT, plan_hash: task.task_package_hash, approval_hash: approval.approval_hash, isolation_hash: "6".repeat(64), worktree_id: execution.worktree_id, write_scope: ["src/a.ts"], command_ids: [...qualityPolicy.command_ids], policy_hash: qualityPolicy.policy_hash, catalog_hash: qualityPolicy.command_registry_hash, fixture_hash: FIXTURE, hidden_root_hash: "c".repeat(64), effective_policy_hash: policy.policy_hash, max_wall_time_ms: qualityPolicy.max_wall_time_ms }; const requestHash = stableHash(request);
  const hiddenBody = { version: 1 as const, command_id: "project_acceptance" as const, approval_boundary_hash: boundaryHash, fixture_hash: FIXTURE, base_commit: COMMIT, counts: options.hiddenFailed ? { passed: 0, failed: 1, not_run: 0 } : { passed: 1, failed: 0, not_run: 0 }, passed: !options.hiddenFailed, exit_code: options.hiddenFailed ? 1 : 0, timed_out: false, output_overflowed: false, hidden_root_unchanged: true, diagnostic_hash: "d".repeat(64), output_summary: options.hiddenFailed ? "Hidden acceptance failed; detailed output remains local-only." : "Hidden acceptance passed; detailed output remains local-only.", redaction_notes: ["hidden_stdout_not_exported", "hidden_stderr_not_exported", "hidden_paths_not_exported", "reference_answer_not_exported"] }; const hidden = { ...hiddenBody, result_hash: stableHash(hiddenBody) };
  const tests = [{ command_id: "unit_tests", exit_code: 0, output_hash: "e".repeat(64), output_summary: "Synthetic visible pass.", timed_out: false, output_overflowed: false, worktree_mutated: false }, { command_id: "project_acceptance", exit_code: hidden.exit_code, output_hash: "f".repeat(64), output_summary: hidden.output_summary, timed_out: false, output_overflowed: false, worktree_mutated: false }];
  const report = { version: 1, run_id: request.run_id, task_id: request.task_id, base_commit: COMMIT, plan_hash: request.plan_hash, approval_hash: request.approval_hash, isolation_hash: request.isolation_hash, worktree_id: request.worktree_id, policy_hash: request.policy_hash, approval_boundary_hash: boundaryHash, catalog_hash: request.catalog_hash, fixture_hash: request.fixture_hash, hidden_root_hash: request.hidden_root_hash, effective_policy_hash: request.effective_policy_hash, max_wall_time_ms: request.max_wall_time_ms, request_hash: requestHash, passed: !options.hiddenFailed, worktree_head: COMMIT, files_changed: ["src/a.ts"], content_snapshot_hash: "7".repeat(64), post_artifact_snapshot_hash: "7".repeat(64), worktree_snapshot_hash: "8".repeat(64), diff_hash: "9".repeat(64), diff_reference: `evidence/${execution.run_id}/${"9".repeat(64)}.diff`, quality_gate_results: gates, tests_run: tests, scope_violations: [], privacy_violations: [], secret_scan_summary: { outcome: "passed" as const, findings: 0, baseline_findings: 0, new_findings: 0 }, wall_clock_time_ms: 0, redaction_notes: ["Synthetic only"], hidden_acceptance_result: hidden };
  const usage = noTelemetry ? { input_tokens: null, output_tokens: null, reasoning_tokens: null, cached_input_tokens: null, cache_write_tokens: null, cache_hit_tokens: null, cache_miss_tokens: null } : { input_tokens: count, output_tokens: count, reasoning_tokens: 0, cached_input_tokens: 0, cache_write_tokens: 0, cache_hit_tokens: 0, cache_miss_tokens: count };
  const acceptanceBody = { version: 1 as const, approval_boundary_hash: boundaryHash, quality_report_hash: stableHash(report), fixture_hash: FIXTURE, base_commit: COMMIT, visible_tests: { passed: 1, failed: 0, not_run: 0 }, hidden_tests: options.hiddenFailed ? { passed: 0, failed: 1, not_run: 0 } : { passed: 1, failed: 0, not_run: 0 }, regression: Boolean(options.hiddenFailed), scope_passed: true, secret_passed: true, diff_passed: true, freeze_passed: true }; const acceptance = { ...acceptanceBody, result_hash: stableHash(acceptanceBody) };
  const bundle: EvidenceBundle = createEvidenceBundle({ version: 4, bundle_id: "pilot-bundle", run_id: execution.run_id, task_id: task.task_id, contract_provenance: "canonical", task_package_hash: task.task_package_hash, route_binding_hash: route.route_binding_hash, policy_hash: policy.policy_hash, quality_policy_hash: qualityPolicy.policy_hash, quality_approval_boundary_hash: boundaryHash, quality_catalog_hash: qualityPolicy.command_registry_hash, fixture_hash: FIXTURE, hidden_root_hash: request.hidden_root_hash, acceptance_results: acceptance, hidden_acceptance_result: hidden, quality_policy: qualityPolicy, approval_hash: approval.approval_hash, execution_context_hash: execution.execution_context_hash, isolation_hash: request.isolation_hash, worktree_id: execution.worktree_id, base_commit: COMMIT, worktree_head: COMMIT, quality_request_hash: requestHash, quality_report_hash: stableHash(report), quality_passed: report.passed, quality_write_scope: ["src/a.ts"], quality_command_ids: [...qualityPolicy.command_ids], post_artifact_snapshot_hash: report.post_artifact_snapshot_hash, worktree_snapshot_hash: report.worktree_snapshot_hash, attempt_ids: attempts.map(item => item.attempt_id), route_evidence_ids: noTelemetry ? [] : ["route-1"], attempt_summaries: attempts.map(item => ({ attempt_id: item.attempt_id, stage: item.stage, status: item.status, failure_class: item.failure_class })), route_evidence_summaries: noTelemetry ? [] : [{ evidence_id: "route-1", provider: route.provider_id, model: route.model_id, verification_status: "route_tuple_verified_peer_unobserved", request_id_present: true }], transport_rounds: rounds, files_changed: report.files_changed, content_snapshot_hash: report.content_snapshot_hash, diff_hash: report.diff_hash, diff_reference: report.diff_reference, quality_gate_results: gates, tests_run: tests, scope_violations: [], privacy_violations: [], secret_scan_summary: report.secret_scan_summary, usage_metrics: usage, cost_metrics: { provider_reported_usd: null, estimated_list_usd: noTelemetry ? null : 0.00000176 * count, invoice_usd: null, chatgpt_quota: null }, pricing_catalog: noTelemetry ? null : { version: PRICING_CATALOG_VERSION, hash: PRICING_CATALOG_HASH, currency: "USD", source_urls: ["https://api-docs.deepseek.com/quick_start/pricing/"], retrieved_at: CREATED, effective_at: CREATED, time_bands: ["peak"] }, wall_clock_time_ms: 0, stage_wall_clock_ms: { plan: null, execute: noTelemetry ? 0 : 10 * count, gate: 0, review: null, repair: 0, total: noTelemetry ? 0 : 10 * count }, repair_count: 0, remaining_risks: ["Offline synthetic evidence"], redaction_notes: ["Synthetic only"] });
  const review = { decision: "PASS" as const, summary: "Synthetic final review passed.", reviewed_at: CREATED, evidence_bundle_hash: bundle.bundle_hash };
  return { arm: options.arm ?? "hybrid", persisted_state: { task_package: task, effective_policy: policy, route_binding: route, execution_context: execution, approval_record: approval, final_review: review, review_history: [review], repair_count: 0, human_interventions: [] }, attempts, evidence_bundle: bundle, observed_main_workspace_snapshot: SNAPSHOT, created_at: CREATED };
}

describe("derived immutable PilotRunRecord", () => {
  it("keeps the checked-in output example strict and self-hashed", async () => { const value = JSON.parse(await readFile(path.join(process.cwd(), "examples", "pilot-run-record.example.json"), "utf8")); expect(() => assertPilotRunRecord(value)).not.toThrow(); });
  it("derives acceptance, visible/hidden results, usage, requests, wall time and four cost layers", () => { const record = createPilotRunRecordFromEvidence(fixture()); expect(record.final_acceptance).toBe(true); expect(record.visible_tests.passed).toBe(1); expect(record.hidden_tests.passed).toBe(1); expect(record.provider_http_request_count).toBe(1); expect(record.usage_by_stage_model[0]?.input_tokens).toBe(1); expect(record.costs).toEqual({ provider_reported_usd: null, estimated_list_usd: 0.00000176, invoice_usd: null, chatgpt_quota: null }); expect(record.recommendation).toBe("simplify"); expect(() => assertPilotRunRecord(record)).not.toThrow(); });
  it("derives hidden failure/regression as a hard stop", () => { const record = createPilotRunRecordFromEvidence(fixture({ hiddenFailed: true })); expect(record.hidden_tests.failed).toBe(1); expect(record.regression).toBe(true); expect(record.final_acceptance).toBe(false); expect(record.recommendation).toBe("stop"); });
  it("derives unexplained duplicate requests instead of accepting a caller claim", () => { const record = createPilotRunRecordFromEvidence(fixture({ duplicate: true })); expect(record.violations.unexplained_duplicate_requests).toBe(1); expect(record.provider_http_request_count).toBe(2); expect(record.final_acceptance).toBe(false); expect(record.recommendation).toBe("stop"); });
  it("preserves unavailable GPT telemetry as null and explicit unavailable reasons", () => { const record = createPilotRunRecordFromEvidence(fixture({ arm: "gpt_only", noTelemetry: true })); expect(record.model).toBeNull(); expect(record.provider_http_request_count).toBeNull(); expect(record.usage_by_stage_model[0]?.input_tokens).toBeNull(); expect(record.costs.estimated_list_usd).toBeNull(); expect(record.core_metrics_unavailable).toEqual(["model", "provider_http_request_count", "token_usage", "estimated_list_cost", "pricing_catalog"]); expect(record.evidence_sufficient).toBe(false); });
  it("rejects EvidenceBundle, attempt and main-snapshot replay/tamper", () => { const source = fixture(); expect(() => createPilotRunRecordFromEvidence({ ...source, attempts: source.attempts.map(item => ({ ...item, run_id: "other-run" })) })).toThrow(/replay|binding/i); const record = createPilotRunRecordFromEvidence(source); expect(() => assertPilotRunRecord({ ...record, final_acceptance: false })).toThrow(/hash|automated|recommendation/); expect(() => assertPilotRunRecord({ ...record, hard_stop: !record.hard_stop })).toThrow(/hard_stop|hash/); const polluted = createPilotRunRecordFromEvidence({ ...source, observed_main_workspace_snapshot: "5".repeat(64) }); expect(polluted.violations.main_workspace_pollution).toBe(1); });
  it("persists immutably, reads only the bound EvidenceBundle, and rejects a colliding replay", async () => { const root = await mkdtemp(path.join(tmpdir(), "pilot-record-")); const record = createPilotRunRecordFromEvidence(fixture()); const target = await persistPilotRunRecord(root, record); expect((await readPilotRunRecord(root, record.task_id, record.run_id, record.evidence_bundle_hash)).record_hash).toBe(record.record_hash); await expect(readPilotRunRecord(root, record.task_id, record.run_id, "f".repeat(64))).rejects.toThrow(/binding/i); const raw = JSON.parse(await readFile(target, "utf8")) as Record<string, unknown>; raw.evidence_bundle_hash = "e".repeat(64); await writeFile(target, JSON.stringify(raw)); await expect(persistPilotRunRecord(root, record)).rejects.toThrow(/hash|replay|collision/); });
  it("binds pair decisions to the two self-hashed runs", () => { const gpt = createPilotRunRecordFromEvidence(fixture({ arm: "gpt_only", noTelemetry: true })); const hybrid = createPilotRunRecordFromEvidence(fixture()); const pair = createPilotPairReport(gpt, hybrid, { same_base_fixture: true, same_scope: true, same_hidden_gate: true, same_wall_budget: true, same_acceptance_criteria: true, created_at: CREATED }); expect(pair.expansion_blockers).toContain("core_evidence_unavailable"); expect(pair.recommendation).toBe("stop"); });
});
